config/routes.rb
Transition::Application.routes.draw do
  resources :organisations do
  	resources :sites
  end

  resources :sites do
    resources :scrape_results, only: [:new, :index, :create, :edit, :update]
    resources :urls, only: [:index, :show, :update]
    resources :urls, only: [:index, :update], as: 'manual_urls', controller: 'manual_urls', path: 'manual_urls'
    get :hits_download, on: :member
    resources :mappings, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :hosts,
    :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
    get :hits_download, on: :member
  end

  resources :pages

  resources :url_groups, only: [:create]
  resources :user_needs, only: [:index, :create, :edit, :update, :destroy]

  match 'dashboard' => 'dashboard#index'

  root :to => 'organisations#index'

  namespace :admin do
    resources :content_types, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { put :set_ordering }
    end
    get 'import_urls' => "import_urls#import"
    post 'import_urls' => "import_urls#import"

    root :to => 'home#index'
  end
end

app/views/transitionsetup/index.html.erb
<h1>Transition Setup</h1>

<br>

To begin transitioning your department, please fill out <a href="https://docs.google.com/a/digital.cabinet-office.gov.uk/spreadsheet/viewform?formkey=dHk0dXRYdFVxZHBVdkRMQ1R4bGdHTWc6MQ#gid=0">this transition questionnaire form</a>.

<br>

<h2>Other links that might be interesting</h2>
<%= link_to 'New Organisation', new_organisation_path %>
<%= link_to 'New Host', new_host_path %>
<%= link_to 'New Site', new_site_path %>