config/routes.rb
Transition::Application.routes.draw do
  resources :organisations do
  	resources :sites
  end

  resources :sites do
    resources :scrape_results, only: [:new, :index, :create, :edit, :update]
    resources :urls, only: [:index, :show, :update]
    resources :urls, only: [:index, :update], as: 'manual_urls', controller: 'manual_urls', path: 'manual_urls'
    get :hits_download, on: :member
    resources :mappings, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :hosts,
    :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
    get :hits_download, on: :member
  end

  resources :pages

  resources :url_groups, only: [:create]
  resources :user_needs, only: [:index, :create, :edit, :update, :destroy]

  match 'dashboard' => 'dashboard#index'

  root :to => 'organisations#index'

  namespace :admin do
    resources :content_types, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { put :set_ordering }
    end
    get 'import_urls' => "import_urls#import"
    post 'import_urls' => "import_urls#import"

    root :to => 'home#index'
  end
end

app/controllers/admin/content_types_controller.rb
class Admin::ContentTypesController < ApplicationController

  def index
    @content_types = ContentType.order(:position)
  end

  def new
    @content_type = ContentType.new
  end

  def create
    @content_type = ContentType.new(params[:content_type])
    if @content_type.save
      redirect_to admin_content_types_path, notice: "Content type '#{@content_type}' saved"
    else
      render action: 'new'
    end
  end

  def edit
    @content_type = ContentType.find(params[:id])
  end

  def update
    @content_type = ContentType.find(params[:id])
    if @content_type.update_attributes(params[:content_type])
      redirect_to admin_content_types_path(@site), notice: "Content type '#{@content_type}' saved"
    else
      render action: 'edit'
    end
  end

  def destroy
    @content_type = ContentType.find(params[:id])
    @content_type.destroy
    redirect_to admin_content_types_path(@site), notice: "Content type '#{@content_type}' deleted"
  end

  def set_ordering
    content_type = ContentType.find(params[:id])
    content_type.insert_at(params[:position].to_i)
    render nothing: true
  end
end

app/views/admin/content_types/_form.html.erb
<h1>Add new content type</h1>

<div class="span6">
  <%= form_for [:admin, @content_type] do |f| %>
    <fieldset>
      <%= render "shared/error_messages", target: f.object %>

      <%= f.label :type %>
      <%= f.text_field :type, autofocus: true, class: 'span6' %>

      <%= f.label :subtype %>
      <%= f.text_field :subtype, class: 'span6' %>

      <label class="checkbox" for="content_type_scrapable">Scrapable 
        <%= f.check_box :scrapable %>
      </label>

      <label class="checkbox" for="content_type_user_need_required">User need required 
        <%= f.check_box :user_need_required %>
      </label>

      <label class="checkbox" for="content_type_mandatory_guidance">Mandatory guidance 
        <%= f.check_box :mandatory_guidance %>
      </label>

      <hr>

      <%= f.submit 'Save new content type', class: 'btn btn-success' %>
    </fieldset>
  <% end %>
</div>

app/views/admin/content_types/index.html.erb
<h1>Content types</h1>

<p>To re-order, drag the Content Type row to the desired position</p>
<p><%= link_to 'Add new content type', new_admin_content_type_path %></p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Type / Subtype</th>
      <th>Scrapable?</th>
      <th>User need required?</th>
      <th>Mandatory guidance?</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody id="sortable" data-update-url="<%= set_ordering_admin_content_types_path %>">
    <% @content_types.each do |content_type| %>
      <%= content_tag_for :tr, content_type do %>
        <td><%= link_to content_type.to_s, edit_admin_content_type_path(content_type) %></td>
        <td><%= content_type.scrapable ? 'Yes' : '' %></td>
        <td><%= content_type.user_need_required ? 'Yes' : '' %></td>
        <td><%= content_type.mandatory_guidance ? 'Yes' : '' %></td>
        <%= content_tag :td, link_to(image_tag('icons/delete.png', width: 16, height: 16), admin_content_type_path(content_type), {method: :delete, confirm: "Delete content type '#{content_type.to_s}'?"}), class: 'delete' %>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= javascript_tag do %>
  $(function() {
    $('#sortable').sortable({
      axis: 'y',
      update: function(event, ui) {
        $.post($(this).data('update-url'), {
          _method: 'put',
          id: ui.item.attr('id').split('_').pop(),
          position: $('tr', this).index(ui.item) + 1
        });
      }
    });
  });
<% end %>

<% content_for :page_title do %>
  Content types
<% end %>