config/routes.rb
Transition::Application.routes.draw do
  resources :organisations do
  	resources :sites
  end

  resources :sites do
    resources :scrape_results, only: [:new, :index, :create, :edit, :update]
    resources :urls, only: [:index, :show, :update]
    resources :urls, only: [:index, :update], as: 'manual_urls', controller: 'manual_urls', path: 'manual_urls'
    get :hits_download, on: :member
    resources :mappings, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :hosts,
    :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
    get :hits_download, on: :member
  end

  resources :pages

  resources :url_groups, only: [:create]
  resources :user_needs, only: [:index, :create, :edit, :update, :destroy]

  match 'dashboard' => 'dashboard#index'

  root :to => 'organisations#index'

  namespace :admin do
    resources :content_types, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { put :set_ordering }
    end
    get 'import_urls' => "import_urls#import"
    post 'import_urls' => "import_urls#import"

    root :to => 'home#index'
  end
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  has_many :sites
  has_many :hosts, through: :sites
  has_many :mappings, through: :sites
  has_many :totals, through: :hosts
  has_many :hits, through: :sites
  has_many :urls, through: :sites
  has_many :url_groups, dependent: :restrict
  has_many :user_needs, dependent: :restrict, order: 'name'

  def self.with_counts
    scoped.
      select('organisations.*, sites_count.count as sites_count, hosts_count.count as hosts_count, mappings_count.count as mappings_count').
      joins('
      left outer JOIN (
        select count(`sites`.id) as count, `sites`.organisation_id
          from `sites`
         group by `sites`.organisation_id
      ) as sites_count ON sites_count.organisation_id = organisations.id

      left outer JOIN (
        select count(`hosts`.id) as count, `sites`.organisation_id
          from `hosts`
         inner join `sites` on `hosts`.site_id = `sites`.id
         group by `sites`.organisation_id
      ) as hosts_count ON hosts_count.organisation_id = organisations.id

      left outer JOIN (
        select count(`mappings`.id) as count, `sites`.organisation_id
          from `mappings`
         inner join `sites` on `mappings`.site_id = `sites`.id
         group by `sites`.organisation_id
      ) as mappings_count ON mappings_count.organisation_id = organisations.id
      ').
      group('organisations.id')
  end

  def weekly_totals
    totals.aggregated_by_week_and_site
  end

  def self.manages_own_redirects
    scoped.where(manages_own_redirects: true)
  end

  def self.gds_manages_redirects
    scoped.where(manages_own_redirects: false)
  end

  def sites_count
    read_attribute('sites_count') || sites.count
  end

  def mappings_count
    read_attribute('mappings_count') || mappings.count
  end

  def hosts_count
    read_attribute('hosts_count') || hosts.count
  end

  def summarise_url_state
    urls.group(:state).count
  end

  def aggregated_totals
    totals.aggregated
  end

  def to_param
    abbr
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

  # GET /organisations
  # GET /organisations.json
  def index
    today = Time.now.change(:hour => 0)

    orgs = Organisation.includes(:sites => :hosts)
    @forthcoming_organisations = orgs.order("launch_date asc").where("launch_date >= ?", today)
    @already_live_organisations = orgs.order("launch_date desc").where("launch_date < ?", today)
    @organisations = []
    @organisations << ["forthcoming", @forthcoming_organisations] if @forthcoming_organisations.length > 0
    @organisations << ["live", @already_live_organisations] if @already_live_organisations.length > 0

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: orgs }
    end
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
    @organisation = Organisation.find_by_abbr(params[:id])
    @counts = @organisation.summarise_url_state
    @total_urls = @counts.values.inject(0) {|sum, n| sum + n}

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/new
  # GET /organisations/new.json
  def new
    @organisation = Organisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/1/edit
  def edit
    @organisation = Organisation.find_by_abbr(params[:id])
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(params[:organisation])

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render json: @organisation, status: :created, location: @organisation }
      else
        format.html { render action: "new" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.json
  def update
    @organisation = Organisation.find_by_abbr(params[:id])

    respond_to do |format|
      if @organisation.update_attributes(params[:organisation])
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation = Organisation.find_by_abbr(params[:id])
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper

  def render_organisation_title(organisation)
    content_tag :h1, id: organisation.abbr, class: "organisation #{organisation.css if organisation.css.present?}" do
      link_to content_tag(:span, organisation.title), organisation
    end
  end
end

app/views/organisations/_organisation.html.erb
<%= content_tag_for :div, organisation do %>
  <td><span id="<%= organisation.abbr %>"><%= organisation.title %></span></td>
  <td><%= organisation.launch_date.to_s(:long_ordinal) %></td>
  <td><%= link_to "View requests", page_path(organisation) %></td>
  <td><%= link_to "View organisation details", organisation_path(organisation) %></td>
<% end %>

app/views/organisations/index.html.erb
<h1>Organisations</h1>

<hr>

<% @organisations.each do |title, orgs| %>

  <h2><%= orgs.length %> Organisations are <%= title %></h2>

  <table class="table table-bordered">
    <thead>
      <th>Organisation</th>
      <th>Launch date</th>
      <th>Requests</th>
      <th>Organisation Details</th>
    </thead>
    <tbody>
      <% orgs.each do |organisation| %>
        <tr>
          <%= render partial: 'organisation', locals: { organisation: organisation } %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<% content_for :page_title do %>
  Organisations
<% end %>

app/views/organisations/show.html.erb
<div class="block">
  <div class="inner-block">
    <div class="organisation-logo">
      <h1 class="organisation<%= " #{@organisation.css}" if @organisation.css.present? %>">
        <span><%= @organisation.title %></span>
      </h1>
    </div>

    <p class="requests-link"><%= link_to "View organisation requests", page_path(@organisation) %></p>

    <dl class="dl-horizontal">
      <dt>Launch date:</dt>
      <dd><%= @organisation.launch_date.try(:to_s, :long_ordinal) %></dd>
      <dt>Homepage:</dt>
      <dd><%= link_to @organisation.homepage, @organisation.homepage %></dd>
      <dt>FURL:</dt>
      <dd><%= link_to @organisation.furl, "http://#{@organisation.furl}" %></dd>
      <dt>Progress:</dt>
      <dd>
        <table>
        <% %w{new unfinished finished}.each do |state| %>
          <tr>
            <td><%= state %></td>
            <td><%= @counts[state] || 0 %></td>
            <td><%= "%.1f" % ((@counts[state] || 0) * 100.0 / @total_urls.to_f) %>%</td>
          </tr>
        <% end %>
        </table>
      </dd>
    </dl>

    <h2>Sites</h2>

    <% @organisation.sites.each do |site| %>
      <%= content_tag_for :div, site do %>
        <h3><%= site.site %></h3>
        <div class="site-links">
          <ul class="inline">
            <li><%= link_to "Requests", page_path(@organisation, site: site.id) %></li>
            <% unless DISABLE_EDITING %>
              <li><%= link_to "Analysis", site_urls_path(site_id: site) %></li>
              <li><%= link_to "Manual", site_manual_urls_path(site_id: site) %></li>
              <li><%= link_to "Mappings", site_mappings_path(site_id: site) %></li>
            <% end %>
          </ul>
        </div>

        <dl class="dl-horizontal">
          <dt>Homepage:</dt>
          <dd><%= link_to site.homepage, site.homepage %></dd>

          <% unless site.query_params.try(:empty?) %>
            <dt>query_params:</dt>
            <dd><%= site.query_params %>
          <% end %>

          <dt>TNA Timestamp</dt>
          <dd><%= site.tna_timestamp %></dd>
        </dl>

        <table class="table table-hover">
          <thead>
            <tr>
              <th>Host</th>
              <th>TTL</th>
              <th>CNAME</th>
              <th>Live CNAME</th>
            </tr>
          </thead>
          <tbody>
            <% site.hosts.each do |host| %>
              <tr>
                <td><%= host.host %></td>
                <td><%= host.ttl %></td>
                <td><%= host.cname %></td>
                <td><%= host.live_cname %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
  </div>
</div>

<% content_for :page_title do %>
  Organisation - <%= @organisation.title %>
<% end %>