config/routes.rb
Transition::Application.routes.draw do
  resources :organisations do
  	resources :sites
  end

  resources :sites do
    resources :scrape_results, only: [:new, :index, :create, :edit, :update]
    resources :urls, only: [:index, :show, :update]
    resources :urls, only: [:index, :update], as: 'manual_urls', controller: 'manual_urls', path: 'manual_urls'
    get :hits_download, on: :member
    resources :mappings, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :hosts,
    :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
    get :hits_download, on: :member
  end

  resources :pages

  resources :url_groups, only: [:create]
  resources :user_needs, only: [:index, :create, :edit, :update, :destroy]

  match 'dashboard' => 'dashboard#index'

  root :to => 'organisations#index'

  namespace :admin do
    resources :content_types, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { put :set_ordering }
    end
    get 'import_urls' => "import_urls#import"
    post 'import_urls' => "import_urls#import"

    root :to => 'home#index'
  end
end

app/models/mapping.rb
require 'digest/sha1'
class Mapping < ActiveRecord::Base
  belongs_to :site
  validates :site, presence: true
  validates :path, presence: true, length: { maximum: 1024 }
  validates :http_status, presence: true, length: { maximum: 3 }
  validates :site_id, uniqueness: { scope: [:path], message: 'Mapping already exists for this site and path!' }, unless: -> { Mapping.leave_uniqueness_check_to_db? }

  # set a hash of the path because we can't have a unique index on
  # the path (it's too long)
  before_validation :set_path_hash
  validates :path_hash, presence: true

  validates :new_url, :suggested_url, :archive_url, length: { maximum: (64.kilobytes - 1) }

  scope :with_status, -> status { where(http_status: Rack::Utils.status_code(status)) }
  scope :redirects, with_status(:moved_permanently)

  def self.leave_uniqueness_check_to_db?
    @leave_uniqueness_check_to_db || false
  end
  def self.leave_uniqueness_check_to_db=(new_value)
    @leave_uniqueness_check_to_db = !!new_value
  end

  def self.with_status(status)
    if status == 'all'
      scoped
    else
      scoped.where(http_status: status)
    end
  end

  def prep_for_import
    set_path_hash
  end
  protected
  def set_path_hash
    self.path_hash = Digest::SHA1.hexdigest(path) if path_changed?
  end
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController

  before_filter :find_site

  def index
    @mappings_data = MappingsData.new(@site.mappings.order(:path))
    @host = @site.default_host

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  def new
    @mapping = @site.mappings.build
  end

  def create
    @mapping = @site.mappings.build(params[:mapping])
    if @mapping.save
      redirect_to site_mappings_path(@site), notice: "Mapping saved"
    else
      render action: 'new'
    end
  end

  def edit
    @mapping = @site.mappings.find(params[:id])
  end

  def update
    @mapping = @site.mappings.find(params[:id])
    if @mapping.update_attributes(params[:mapping])
      redirect_to site_mappings_path(@site), notice: "Mapping saved"
    else
      render action: 'edit'
    end
  end

  def destroy
    @mapping = @site.mappings.find(params[:id])
    @mapping.destroy
    redirect_to site_mappings_path(@site), notice: "Mapping deleted"
  end
end

app/views/mappings/_form.html.erb
<h1>New mapping</h1>

<%= form_for @mapping, url: polymorphic_path([@site, @mapping]) do |f| %>
  <fieldset class="span6">
    <%= render "shared/error_messages", target: f.object %>

      <%= f.label :path %>
      <%= f.text_field :path, class: 'span6' %>

      <%= f.label :new_url %>
      <%= f.text_field :new_url, class: 'span6' %>

      <%= f.label :suggested_url %>
      <%= f.text_field :suggested_url, class: 'span6' %>

      <%= f.label :archive_url %>
      <%= f.text_field :archive_url, class: 'span6' %>

      <%= f.label :http_status %>
      <%= f.select :http_status, ['301', '410'] %>

      <hr>

    <%= f.submit 'Save mapping', class: 'btn btn-success' %>
  </fieldset>
<% end %>

<% content_for :page_title do %>
  New mapping
<% end %>

app/views/mappings/index.html.erb
<div class="block">
  <div class="inner-block">

    <%= render 'sites/header', site: @site, organisation: @site.organisation, with_site_link: true %>

    <section class="mappings status-filtering">
      <h1>Mappings</h1>

      <dl class="dl-horizontal">
        <dt>Total</dt>
        <dd><%= number_with_delimiter (@mappings_data.count) %></dd>
      </dl>

      <p><%= link_to 'New Mapping', new_site_mapping_path(@site), class: 'button' %></p>

      <div class="progress status-chart">
        <% @mappings_data.counts_by_http_status.each do |status, status_count| %>
            <div class="bar bar-<%= status %>" style="width: <%= number_to_percentage((status_count / @mappings_data.count.to_f) * 100.0) %>%" title="Status: <%= status %>, count: <%= status_count %>"></div>
        <% end %>
      </div>

      <ul class="status-filter nav filter-block">
        <li class="active"><a href="#" data-toggle="tab" data-status-code="all">All</a></li>
        <% @mappings_data.http_statuses.each do |status_code| %>
            <li><a href="#" data-toggle="tab" data-status-code="<%= status_code %>"><%= status_code %></a></li>
        <% end %>
      </ul>

      <table class="status-filtered hit-table table table-bordered">
        <thead>
        <tr>
          <th>Edit Mapping</th>
          <th>HTTP Status</th>
          <th>Original URL</th>
          <th>New URL</th>
          <th>Suggested URL</th>
          <th>Archive URL</th>
          <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        <% @mappings_data.mappings.each do |mapping| %>
            <tr data-status-code="<%= mapping.http_status %>">
              <td><%= link_to 'Edit', edit_site_mapping_path(@site, mapping) %></td>
              <td><%= mapping.http_status %></td>
              <td><%= link_to mapping.path, 'http://'+@host.host+mapping.path %></td>
              <td><%= link_to mapping.new_url, mapping.new_url if mapping.new_url.present? %></td>
              <td><%= link_to mapping.suggested_url, mapping.suggested_url if mapping.suggested_url.present? %></td>
              <td><%= link_to mapping.archive_url, mapping.archive_url if mapping.archive_url.present? %></td>
              <%= content_tag :td, link_to(image_tag('icons/delete.png', width: 16, height: 16), site_mapping_path(@site, mapping), {method: :delete, confirm: "Delete mapping for '#{mapping.path}'?"}), class: 'delete' %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </section>

  </div>
</div>